config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments, only: [:create]
  end
    resources :likes, only: [:create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: {scope: :post_id}
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.new(comment_params)
    if !@comment.save
      flash[:notice] = @comment.errors.full_messages.to_sentence
    end
    redirect_to post_path(params[:post_id])
  end
  
  private
  def comment_params
    params.require(:comment).permit(:content).merge(post_id: params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new(like_params)
    if !@like.save
      flash[:notice] = @like.errors.full_messages.to_sentence
    end
    redirect_to @like.post
  end

  def destroy
    @like = current_user.likes.find(params[:id])
    post = @like.post
    @like.destroy
    redirect_to post
  end

  def like_params
    params.require(:like).permit(:post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!,except:[:index]
  # before_action :ensure_current_user
  # GET /posts or /posts.json
  def index
    if user_signed_in?
      @posts = Post.where(user_id: current_user)
  else
      @posts = Post.all
  end
    # @posts = current_user.posts
  end

  # GET /posts/1 or /posts/1.json
  def show

  end

  # GET /posts/new
  def new
      # @post = Post.new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
      # @post = Post.new(post_params)
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<!-- <strong>Comments</strong>
<br/> -->
<article>
  <p> <%= comment.content%> </p>
  <small> <b>by <%= comment.user.email%></b> </small>
</article>
<hr />

app/views/comments/_form.html.erb
<%= @post.comments.count%>
<div class="container-fluid">
<form action="<%= post_comments_path(@post)%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<input type="text" name="comment[content]" rows="1" cols="40"placeholder="Add Comment">
  <input type = "submit" value="Comment" class = 'btn btn-outline-warning btn-sm'>
  </form>
  </div>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
<div class="container-fluid">
  <a class="navbar-brand" href=#>The Blog App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item hover">
        <a class="nav-link" href="/posts">Posts</a>
      </li>
      <li class="nav-item hover">
        <a class="nav-link" href="/posts/new">Add New Post</a>
      </li>
      </ul>
    <% if user_signed_in? %>
          <%= link_to "Edit", edit_user_registration_path,:class => 'navbar-link',:class => 'btn btn-warning' %>  |
          <%= button_to "Logout", destroy_user_session_path, method: :delete,:class => 'btn btn-warning'%>
      <% else %>
          <%= link_to "Sign up", new_user_registration_path,:class => 'navbar-link',:class => 'btn btn-warning' %>  |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link',:class => 'btn btn-warning' %>
      <% end %>
    </div>
 </div>
</nav>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
<br/>
      <div class="container">
  <% if notice %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
</div>
<br>
<div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>


  <div>
    <%= form.number_field :user_id, id: :post_user_id, value: current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

  <div>
    <%= link_to "Edit", edit_post_path(@post) %> |
    <%= link_to "Back", posts_path %>
  </div>
<br/>
<%= @post.likes.count%> Likes <br/>
<% if current_user.likes.find_by(post: @post).nil? %>
  <div class="container-fluid">
  <form action="/likes" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="like[post_id]" value="<%= @post.id %>">
    <input type = "submit" value="Like" class = 'btn btn-outline-warning btn-sm'>
    </form>
    </div>
    <% else %>
    <div class="container-fluid">
    <form action="<%= likes_path(@like) %>" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="hidden" name="_method" value="Delete">
      <input type = "submit" value="Unlike" class = 'btn btn-outline-warning btn-sm'>
      </form>
      </div>
    <% end %>
<br/>
  <p>
    <strong>Comments :</strong>
      <%= render partial: 'comments/form', locals:{post: @post} %>
      <%= render @post.comments.order(id: :desc) %>
  </p>
  <br>

  <br/>
  <br/>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>
<br/>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <!-- <th>Comments</th> -->
       <th colspan="1"></th>
      </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
     <tr>
      <td><%= post.title%></td>
      <td><%= post.body%></td>
      <td><%= link_to "View",post,:class => 'btn btn-outline-primary btn-sm'%></td>
     </tr>
     <% end %>
</tbody>
</table>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>